import { formatMoney, safeFileSegment, downloadCsv, toInputDate } from "./util.js";
import { DEFAULT_COMPANY } from "./companyProfile.js";

function escapeHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function safeLogoHtml(company) {
  const u = company?.logoDataUrl;
  if (typeof u !== "string" || u.length > 800000) return "";
  if (!/^data:image\/(png|jpeg|jpg|gif|webp);base64,/i.test(u)) return "";
  return `<img src="${u.replace(/"/g, "")}" alt="" style="max-height:52px;max-width:120px;object-fit:contain" />`;
}

const UNIT_LABELS = { bottle: "Bottle", box: "Box", kg: "Kg", piece: "Piece" };

export const INVENTORY_STORES = ["Store 1", "Store 2", "Store 3"];

export function inventoryUnitLabel(u) {
  return UNIT_LABELS[u] || u || "—";
}

const STYLES = `
  @page { size: A4 portrait; margin: 12mm; }
  html, body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1f2937; margin: 0; font-size: 10pt; }
  .wrap { padding: 4px 6px; }
  .letterhead {
    display: grid; grid-template-columns: auto 1fr; gap: 14px;
    align-items: center; padding-bottom: 12px;
    border-bottom: 2px solid #1d6c8f; margin-bottom: 14px;
  }
  .letterhead .co .legal { font-size: 13pt; font-weight: 700; color: #1d6c8f; margin: 0 0 4px; }
  .letterhead .co .addr, .letterhead .co .contact { font-size: 9.5pt; color: #4b5563; margin: 0; }
  .docTitle { font-size: 14pt; font-weight: 700; color: #1b6484; margin: 0 0 4px; }
  .docSubtitle { font-size: 10pt; color: #6b7280; margin: 0 0 14px; }
  .summary {
    display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 8px; margin-bottom: 14px;
  }
  .summary .box {
    border: 1px solid #c8d0d8; padding: 8px 10px; background: #f8fafc;
  }
  .summary .box .lbl { font-size: 8.5pt; color: #6b7280; }
  .summary .box .val { font-size: 12pt; font-weight: 700; margin-top: 2px; }
  table.inv { border-collapse: collapse; width: 100%; }
  table.inv th, table.inv td {
    border: 1px solid #c8d0d8; padding: 5px 7px; font-size: 9pt; vertical-align: top;
  }
  table.inv th { background: #b9d8ea; font-weight: 700; text-align: left; }
  table.inv td.num, table.inv th.num { text-align: right; white-space: nowrap; }
  table.inv tr.low td { background: #fff1f0; }
  table.inv tr.expiring td { background: #fff8e6; }
  .blank { min-width: 48px; border-bottom: 1px solid #9ca3af; display: inline-block; height: 14px; }
  .footerNote {
    margin-top: 20px; padding-top: 8px; border-top: 1px solid #d1d5db;
    font-size: 8.5pt; color: #6b7280; text-align: center;
  }
  .muted { color: #6b7280; }
  .sectionTitle {
    font-size: 10pt; font-weight: 700; color: #1d6c8f;
    margin: 16px 0 8px; text-transform: uppercase; letter-spacing: 0.3px;
  }
`;

function wrapHtml(title, body, company = DEFAULT_COMPANY) {
  const c = company || DEFAULT_COMPANY;
  const logo = safeLogoHtml(c);
  const address = [c.addressLine1, c.addressLine2, c.city].filter(Boolean).map(escapeHtml).join(", ");
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>${STYLES}</style>
</head>
<body>
  <div class="wrap">
    <div class="letterhead">
      ${logo ? `<div>${logo}</div>` : ""}
      <div class="co">
        <p class="legal">${escapeHtml(c.legalName || c.brandName || "Samakaab")}</p>
        ${address ? `<p class="addr">${address}</p>` : ""}
        <p class="contact">${escapeHtml([c.phone && `Tel: ${c.phone}`, c.email && `Email: ${c.email}`].filter(Boolean).join(" · "))}</p>
      </div>
    </div>
    ${body}
    <p class="footerNote">Generated by ${escapeHtml(c.brandName || c.legalName)} on ${escapeHtml(new Date().toLocaleString())}.</p>
  </div>
</body>
</html>`;
}

export function printInventoryHtml(html) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => {
    w.print();
    w.close();
  }, 300);
}

function daysUntil(d) {
  if (!d) return null;
  const end = new Date(d);
  end.setHours(0, 0, 0, 0);
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  return Math.round((end - start) / 86400000);
}

function statusForProduct(p, expiryDays = 30) {
  if (p.lowStock) return "Low";
  const days = daysUntil(p.nearestExpiry);
  if (days != null && days >= 0 && days <= expiryDays) return "Expiring";
  if (days != null && days < 0) return "Expired";
  return "OK";
}

function rowClass(p, expiryDays = 30) {
  const s = statusForProduct(p, expiryDays);
  if (s === "Low" || s === "Expired") return "low";
  if (s === "Expiring") return "expiring";
  return "";
}

/** @param {"all"|"low"|"expiring"|"closing"} kind */
export function buildInventoryListHtml(products, company, { kind = "all", expiryDays = 30, title } = {}) {
  const list = products || [];
  const today = new Date().toLocaleDateString();
  const lowCount = list.filter((p) => p.lowStock).length;
  const costTotal = list.reduce((s, p) => s + (Number(p.costValue) || 0), 0);
  const sellTotal = list.reduce((s, p) => s + (Number(p.sellValue) || 0), 0);

  const titles = {
    all: "INVENTORY LIST",
    low: "LOW STOCK REPORT",
    expiring: `EXPIRING SOON (within ${expiryDays} days)`,
    closing: "DAILY CLOSING SHEET",
  };
  const docTitle = title || titles[kind] || "INVENTORY";

  const isClosing = kind === "closing";
  const headCols = isClosing
    ? `<th>#</th><th>Product</th><th>Unit</th><th class="num">On hand</th><th class="num">Sold today</th><th class="num">Remaining</th>`
    : `<th>#</th><th>Product</th><th>Store</th><th>Unit</th><th class="num">Remaining</th><th class="num">Sell price</th><th>Nearest expiry</th><th>Status</th>`;

  const rows = list
    .map((p, i) => {
      if (isClosing) {
        return `<tr>
          <td>${i + 1}</td>
          <td>${escapeHtml(p.name)}</td>
          <td>${escapeHtml(inventoryUnitLabel(p.unit))}</td>
          <td class="num">${escapeHtml(String(p.quantityRemaining ?? 0))}</td>
          <td class="num"><span class="blank"></span></td>
          <td class="num"><span class="blank"></span></td>
        </tr>`;
      }
      return `<tr class="${rowClass(p, expiryDays)}">
        <td>${i + 1}</td>
        <td>${escapeHtml(p.name)}</td>
        <td>${escapeHtml(p.store || "—")}</td>
        <td>${escapeHtml(inventoryUnitLabel(p.unit))}</td>
        <td class="num">${escapeHtml(String(p.quantityRemaining ?? 0))}</td>
        <td class="num">${Number(p.sellPrice) > 0 ? escapeHtml(formatMoney(p.sellPrice)) : "—"}</td>
        <td>${p.nearestExpiry ? escapeHtml(toInputDate(p.nearestExpiry)) : "—"}</td>
        <td>${escapeHtml(statusForProduct(p, expiryDays))}</td>
      </tr>`;
    })
    .join("");

  const body = `
    <h1 class="docTitle">${escapeHtml(docTitle)}</h1>
    <p class="docSubtitle">Report date: ${escapeHtml(today)} · ${list.length} product${list.length === 1 ? "" : "s"}</p>
    ${
      !isClosing
        ? `<div class="summary">
      <div class="box"><div class="lbl">Products</div><div class="val">${list.length}</div></div>
      <div class="box"><div class="lbl">Low stock</div><div class="val">${lowCount}</div></div>
      <div class="box"><div class="lbl">Stock value (cost)</div><div class="val">${escapeHtml(formatMoney(costTotal))}</div></div>
      <div class="box"><div class="lbl">Stock value (sell)</div><div class="val">${escapeHtml(formatMoney(sellTotal))}</div></div>
    </div>`
        : `<p class="muted">Fill “Sold today” at closing, then enter those numbers in the system (Record sold).</p>`
    }
    <table class="inv">
      <thead><tr>${headCols}</tr></thead>
      <tbody>
        ${rows || `<tr><td colspan="7" class="muted">No products.</td></tr>`}
      </tbody>
    </table>`;

  return wrapHtml(docTitle, body, company);
}

export function buildProductStockCardHtml(product, batches, movements, company) {
  const p = product || {};
  const today = new Date().toLocaleDateString();
  const batchRows = (batches || [])
    .map(
      (b) => `<tr>
      <td>${escapeHtml(toInputDate(b.receivedAt))}</td>
      <td class="num">${escapeHtml(String(b.quantityRemaining))}</td>
      <td class="num">${escapeHtml(String(b.quantityReceived))}</td>
      <td>${b.expiryDate ? escapeHtml(toInputDate(b.expiryDate)) : "—"}</td>
      <td>${escapeHtml(b.supplier || "—")}</td>
      <td class="num">${Number(b.unitCost) > 0 ? escapeHtml(formatMoney(b.unitCost)) : "—"}</td>
    </tr>`
    )
    .join("");

  const moveRows = (movements || [])
    .slice(0, 25)
    .map(
      (m) => `<tr>
      <td>${escapeHtml(toInputDate(m.date))}</td>
      <td>${escapeHtml(m.type)}</td>
      <td class="num">${escapeHtml(String(m.quantity))}</td>
      <td>${escapeHtml(m.supplier || "—")}</td>
      <td>${escapeHtml(m.note || "—")}</td>
      <td>${escapeHtml(m.createdBy || "—")}</td>
    </tr>`
    )
    .join("");

  const body = `
    <h1 class="docTitle">STOCK CARD</h1>
    <p class="docSubtitle">${escapeHtml(p.name)} · ${escapeHtml(inventoryUnitLabel(p.unit))} · ${escapeHtml(today)}</p>
    <div class="summary">
      <div class="box"><div class="lbl">Remaining</div><div class="val">${escapeHtml(String(p.quantityRemaining ?? 0))}</div></div>
      <div class="box"><div class="lbl">Sell price</div><div class="val">${Number(p.sellPrice) > 0 ? escapeHtml(formatMoney(p.sellPrice)) : "—"}</div></div>
      <div class="box"><div class="lbl">Cost value</div><div class="val">${escapeHtml(formatMoney(p.costValue ?? 0))}</div></div>
      <div class="box"><div class="lbl">Status</div><div class="val">${p.lowStock ? "Low stock" : "OK"}</div></div>
    </div>
    <div class="sectionTitle">Open batches</div>
    <table class="inv">
      <thead><tr><th>Received</th><th class="num">Remaining</th><th class="num">Of</th><th>Expiry</th><th>Store</th><th class="num">Cost</th></tr></thead>
      <tbody>${batchRows || `<tr><td colspan="6" class="muted">No open batches.</td></tr>`}</tbody>
    </table>
    <div class="sectionTitle">Recent movements</div>
    <table class="inv">
      <thead><tr><th>Date</th><th>Type</th><th class="num">Qty</th><th>Store</th><th>Note</th><th>By</th></tr></thead>
      <tbody>${moveRows || `<tr><td colspan="6" class="muted">No movements.</td></tr>`}</tbody>
    </table>`;

  return wrapHtml(`${p.name} — stock card`, body, company);
}

export function buildStockInReceiptHtml(product, batch, company) {
  const p = product || {};
  const b = batch || {};
  const body = `
    <h1 class="docTitle">STOCK-IN RECEIPT</h1>
    <p class="docSubtitle">Goods received · ${escapeHtml(new Date(b.receivedAt || Date.now()).toLocaleDateString())}</p>
    <table class="inv">
      <tbody>
        <tr><td>Product</td><td><strong>${escapeHtml(p.name)}</strong></td></tr>
        <tr><td>Unit</td><td>${escapeHtml(inventoryUnitLabel(p.unit))}</td></tr>
        <tr><td>Quantity received</td><td class="num"><strong>${escapeHtml(String(b.quantityReceived ?? b.quantityRemaining ?? ""))}</strong></td></tr>
        <tr><td>Unit cost</td><td class="num">${Number(b.unitCost) > 0 ? escapeHtml(formatMoney(b.unitCost)) : "—"}</td></tr>
        <tr><td>Store</td><td>${escapeHtml(b.supplier || "—")}</td></tr>
        <tr><td>Expiry</td><td>${b.expiryDate ? escapeHtml(toInputDate(b.expiryDate)) : "—"}</td></tr>
        <tr><td>Note</td><td>${escapeHtml(b.note || "—")}</td></tr>
        <tr><td>Entered by</td><td>${escapeHtml(b.createdBy || "—")}</td></tr>
      </tbody>
    </table>`;
  return wrapHtml(`Stock-in — ${p.name}`, body, company);
}

export function downloadInventoryCsv(products, filename = "inventory") {
  const header = [
    "Product",
    "Store",
    "Unit",
    "Remaining",
    "Sell price",
    "Cost value",
    "Sell value",
    "Nearest expiry",
    "Low stock",
    "Status",
  ];
  const rows = (products || []).map((p) => [
    p.name,
    p.store || "",
    inventoryUnitLabel(p.unit),
    p.quantityRemaining ?? 0,
    p.sellPrice ?? 0,
    p.costValue ?? 0,
    p.sellValue ?? 0,
    p.nearestExpiry ? toInputDate(p.nearestExpiry) : "",
    p.lowStock ? "yes" : "no",
    statusForProduct(p),
  ]);
  downloadCsv(`${safeFileSegment(filename)}.csv`, header, rows);
}

export function filterInventoryProducts(products, { filter = "all", expiryDays = 30, store = "" } = {}) {
  let list = products || [];
  if (store) list = list.filter((p) => p.store === store);
  if (filter === "low") return list.filter((p) => p.lowStock);
  if (filter === "expiring") {
    return list.filter((p) => {
      const d = daysUntil(p.nearestExpiry);
      return d != null && d <= expiryDays;
    });
  }
  return list;
}
