import { formatMoney, safeFileSegment } from "./util.js";
import { DEFAULT_COMPANY } from "./companyProfile.js";

function escapeHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function safeLogoHtml(company) {
  const u = company?.logoDataUrl;
  if (typeof u !== "string" || u.length > 800000) return "";
  if (!/^data:image\/(png|jpeg|jpg|gif|webp);base64,/i.test(u)) return "";
  return `<img src="${u.replace(/"/g, "")}" alt="" style="max-height:52px;max-width:120px;object-fit:contain" />`;
}

const REPORT_STYLES = `
  @page { size: A4 portrait; margin: 12mm; }
  html, body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { font-family: Arial, Helvetica, sans-serif; color: #1f2937; margin: 0; font-size: 10.5pt; }
  .wrap { padding: 4px 6px; }
  .letterhead {
    display: grid; grid-template-columns: auto 1fr; gap: 14px;
    align-items: center; padding-bottom: 12px;
    border-bottom: 2px solid #1d6c8f; margin-bottom: 14px;
  }
  .letterhead .co { line-height: 1.45; }
  .letterhead .co .legal { font-size: 13pt; font-weight: 700; color: #1d6c8f; margin: 0 0 4px; }
  .letterhead .co .addr { font-size: 9.5pt; color: #4b5563; margin: 0; }
  .letterhead .co .contact { font-size: 9.5pt; color: #4b5563; margin: 4px 0 0; }
  .docTitleRow {
    display: grid; grid-template-columns: 1fr auto; gap: 12px;
    align-items: start; margin-bottom: 16px;
  }
  .docTitle { font-size: 14pt; font-weight: 700; color: #1b6484; letter-spacing: 0.5px; margin: 0; }
  .docSubtitle { font-size: 10pt; color: #6b7280; margin: 4px 0 0; }
  .periodBox {
    min-width: 200px; border: 1px solid #9ca3af; font-size: 9.5pt;
  }
  .periodBox .head {
    background: #1d6c8f; color: #fff; padding: 5px 10px; font-weight: 700; text-align: center;
  }
  .periodBox .row {
    display: grid; grid-template-columns: 1fr auto; gap: 8px;
    padding: 4px 10px; border-bottom: 1px solid #d1d5db;
  }
  .periodBox .row:last-child { border-bottom: none; }
  .sectionTitle {
    font-size: 10pt; font-weight: 700; color: #1d6c8f;
    margin: 18px 0 8px; padding-bottom: 4px;
    border-bottom: 1px solid #b9d8ea; text-transform: uppercase; letter-spacing: 0.4px;
  }
  table.report { border-collapse: collapse; width: 100%; table-layout: fixed; }
  table.report th, table.report td {
    border: 1px solid #c8d0d8; padding: 6px 8px; font-size: 9.5pt; vertical-align: top;
  }
  table.report th { background: #b9d8ea; font-weight: 700; text-align: left; }
  table.report td.amount, table.report th.amount { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
  table.report tr.total td { font-weight: 700; background: #f2f4f6; }
  .footerNote {
    margin-top: 24px; padding-top: 10px; border-top: 1px solid #d1d5db;
    font-size: 8.5pt; color: #6b7280; text-align: center;
  }
  .muted { color: #6b7280; }
`;

function summaryRowsHtml(rows) {
  return rows
    .map(
      ([label, value, bold]) =>
        `<tr${bold ? ' class="total"' : ""}><td>${escapeHtml(label)}</td><td class="amount">${escapeHtml(value)}</td></tr>`
    )
    .join("");
}

function debtorsRowsHtml(debtors, showPhone) {
  if (!debtors?.length) {
    return `<tr><td colspan="${showPhone ? 3 : 2}" class="muted">No outstanding customer balances.</td></tr>`;
  }
  return debtors
    .map(
      (c, i) =>
        `<tr>
      <td>${i + 1}</td>
      <td>${escapeHtml(c.fullName)}${showPhone && c.phone ? `<br/><span class="muted">${escapeHtml(c.phone)}</span>` : ""}</td>
      <td class="amount">${escapeHtml(formatMoney(c.balance))}</td>
    </tr>`
    )
    .join("");
}

function wrapReportHtml(title, bodyInner, company) {
  const c = company || DEFAULT_COMPANY;
  const today = new Date().toLocaleDateString();
  const address = (c.addressLines || []).map((l) => escapeHtml(l)).join("<br/>");
  const logo = safeLogoHtml(c);
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>${REPORT_STYLES}</style>
</head>
<body>
  <div class="wrap">
    <div class="letterhead">
      ${logo ? `<div>${logo}</div>` : ""}
      <div class="co">
        <p class="legal">${escapeHtml(c.legalName)}</p>
        ${address ? `<p class="addr">${address}</p>` : ""}
        <p class="contact">${escapeHtml([c.phone && `Tel: ${c.phone}`, c.email && `Email: ${c.email}`].filter(Boolean).join(" · "))}</p>
      </div>
    </div>
    ${bodyInner}
    <p class="footerNote">This report was generated by ${escapeHtml(c.brandName || c.legalName)} credit system on ${escapeHtml(today)}.</p>
  </div>
</body>
</html>`;
}

export function buildMonthlyReportHtml(data, company, { monthLabel, year }) {
  const invCount = data.transactionCounts?.invoices ?? 0;
  const summary = [
    ["Total sales (invoices)", formatMoney(data.totalSales ?? 0)],
    ["Cash received at sale", formatMoney(data.totalPaidAtSale ?? 0)],
    ["Payments recorded (later)", formatMoney(data.totalPaymentsRecorded ?? 0)],
    ["Credit given (new debt)", formatMoney(data.totalCreditGiven ?? 0)],
    ["Total money received", formatMoney(data.totalMoneyReceived ?? 0), true],
    ["Outstanding balance (all customers, as of today)", formatMoney(data.totalOutstandingBalance ?? 0), true],
  ];

  const body = `
    <div class="docTitleRow">
      <div>
        <h1 class="docTitle">MANAGEMENT REPORT</h1>
        <p class="docSubtitle">Monthly financial summary — ${escapeHtml(monthLabel)} ${year}</p>
      </div>
      <div class="periodBox">
        <div class="head">REPORT PERIOD</div>
        <div class="row"><span>Month</span><strong>${escapeHtml(monthLabel)} ${year}</strong></div>
        <div class="row"><span>Invoices</span><strong>${invCount}</strong></div>
        <div class="row"><span>Report date</span><strong>${escapeHtml(new Date().toLocaleDateString())}</strong></div>
      </div>
    </div>

    <div class="sectionTitle">Summary</div>
    <table class="report">
      <thead><tr><th>Description</th><th class="amount">Amount (USD)</th></tr></thead>
      <tbody>${summaryRowsHtml(summary)}</tbody>
    </table>

    <div class="sectionTitle">Customers with outstanding balance</div>
    <table class="report">
      <thead><tr><th style="width:36px">#</th><th>Customer</th><th class="amount">Balance owed</th></tr></thead>
      <tbody>${debtorsRowsHtml(data.customersWhoOwe, true)}</tbody>
    </table>`;

  return wrapReportHtml(`${monthLabel} ${year} — Management Report`, body, company);
}

export function buildYearlyReportHtml(data, company, { year, monthLabels }) {
  const invCount = data.transactionCounts?.invoices ?? 0;
  const summary = [
    ["Total sales (invoices)", formatMoney(data.yearlyTotalSales ?? 0)],
    ["Cash received at sale", formatMoney(data.yearlyTotalPaidAtSale ?? 0)],
    ["Payments recorded (later)", formatMoney(data.yearlyPaymentsRecorded ?? 0)],
    ["Credit given (new debt)", formatMoney(data.yearlyCreditTotal ?? 0)],
    ["Total money received", formatMoney(data.yearlyMoneyReceived ?? 0), true],
  ];

  const monthRows = (data.salesTrendsByMonth || [])
    .map(
      (row) =>
        `<tr>
      <td>${escapeHtml(monthLabels[row.month - 1] || `Month ${row.month}`)}</td>
      <td class="amount">${escapeHtml(formatMoney(row.totalSales ?? 0))}</td>
      <td class="amount">${escapeHtml(formatMoney(row.paidAtSale ?? 0))}</td>
    </tr>`
    )
    .join("");

  const body = `
    <div class="docTitleRow">
      <div>
        <h1 class="docTitle">MANAGEMENT REPORT</h1>
        <p class="docSubtitle">Annual financial summary — ${year}</p>
      </div>
      <div class="periodBox">
        <div class="head">REPORT PERIOD</div>
        <div class="row"><span>Year</span><strong>${year}</strong></div>
        <div class="row"><span>Invoices</span><strong>${invCount}</strong></div>
        <div class="row"><span>Report date</span><strong>${escapeHtml(new Date().toLocaleDateString())}</strong></div>
      </div>
    </div>

    <div class="sectionTitle">Summary</div>
    <table class="report">
      <thead><tr><th>Description</th><th class="amount">Amount (USD)</th></tr></thead>
      <tbody>${summaryRowsHtml(summary)}</tbody>
    </table>

    ${
      monthRows
        ? `<div class="sectionTitle">Sales by month</div>
    <table class="report">
      <thead><tr><th>Month</th><th class="amount">Total sales</th><th class="amount">Cash at sale</th></tr></thead>
      <tbody>${monthRows}</tbody>
    </table>`
        : ""
    }

    <div class="sectionTitle">Top customers with outstanding balance</div>
    <table class="report">
      <thead><tr><th style="width:36px">#</th><th>Customer</th><th class="amount">Balance owed</th></tr></thead>
      <tbody>${debtorsRowsHtml(data.biggestDebtors, false)}</tbody>
    </table>`;

  return wrapReportHtml(`${year} — Management Report`, body, company);
}

export function printReportFromHtml(html) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => {
    w.print();
    w.close();
  }, 350);
}

export function downloadReportWord(html, filename) {
  const blob = new Blob(["\ufeff", html], { type: "application/msword;charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export function downloadReportPdfViaPrint(html) {
  printReportFromHtml(html);
}
